spring:
 datasource:
   driverClassName: org.postgresql.Driver
   url: jdbc:postgresql://localhost:5433/magic
   username: postgres
   password: postgres

 jpa:
   hibernate.ddl-auto: create-drop
   hibernate.dialect: true
   generate-ddl: true
   show-sql: true
   